### PR TITLE
CON-309 CON-310 | Update Windows & Linux architecture

### PR DESCRIPTION
**Pull request by ManuelJNunez**
This PR is to update the windows architecture for the next release.

### CODE REVIEW

**Review by elainerti — COMMENTED** [review]
We are switching base arch from x64WinVS2015 to x64Win64VS2017, and from x64Linux3gcc4.8.2 to x64Linux4gcc7.3.0 
We are NOT removing x64Win64VS2015 or x64Linux3gcc4.8.2 -- they are just not used as base arch to build the host.
Given that, do we need to change connector-js or not?

**Comment by ManuelJNunez** [comment]
> We are switching base arch from x64WinVS2015 to x64Win64VS2017, and from x64Linux3gcc4.8.2 to x64Linux4gcc7.3.0 
> We are NOT removing x64Win64VS2015 or x64Linux3gcc4.8.2 -- they are just not used as base arch to build the host.
> Given that, do we need to change connector-js or not?
I understand, in that case I don't think it is necessary to update the connector architectures

**Comment by elainerti** [comment]
We don't "need to". Do we "want to" change it even if it is not needed?

**Comment by Alxe** [comment]
@elainerti I understand your concerns but let's do this change to have alignment between Connector and Connext.

**Review by alejnp — APPROVED** [review]

**Comment by alejnp** [comment]
This configuration has been merged externally to Github.

**Pull request closed without merging**
